# Configuration
# ===============

# Page name
name: C++
# Description of the page/course
description: Open course for C++
# Github repository hosting this page/course
github: https://github.com/uni-oer/uni-oer.github.io
# Google analytics
analytics: UA-xxxxxxxx-x
# ex. GitHub pages URL
url: http://uni-oer.github.io

# Already set as defaults in jekyll > 2.4.x
# highlighter: pygments
# markdown: kramdown
# include: ['.htaccess']

# Default layouts for posts and pages
defaults:
  -
    scope: 
      path: "domains"
    values:
      layout: "module"

# SASS partial directory and output parameters
sass:
  sass_dir: _sass
  style: :compressed

# Use RSS?
rss: false

# Files to be excluded (feel free to exclude files like: search.json, rss.xml, humans.txt, etc.)
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE.txt']
